### PR TITLE
Switch to Payment.create to fix issues with payment_instrument_id on payments

### LINKED ISSUE #63: Payment Method is null for recurring GoCardless payment
I've just been trying to set up a smart group (using Advanced Search) with the following criteria:

- Contribution Status = Completed
- Contribution Payment Method = "GoCardless Direct Debit"
AND (under the Recurring payments fieldset)
- Recurring Payment Start Date = last 30 days

This causes errors ("DB error: unknown error") and then all smart groups appear to break.

If I use Receive Date = last 30 days instead of Recurring Payments = last 30 days, it's fine. 

When I look through the error log, I did notice "Ignoring exception thrown by nullHandler: -1, DB Error: unknown error". I also noticed, when poking around, that the Payment Method for the transaction (not the contribution) is null, despite being a mandatory field (see screenshot).

Untitled

Site is running WordPress 5.3.2 and CiviCRM 5.19.4 and GoCardless extension 1.8

### PR DESCRIPTION
**Pull request by mattwire**
@artfulrobot This fixes #63. I started debugging and then thought what happens if I switch to the new preferred api `Payment.create` instead of completetransaction. And by magic it works perfectly.

`Payment.create` calls completetransaction internally if required. As this is now our preferred, tested route for completing a transaction it makes sense to switch rather than investigate a broken "legacy" code-path.

### CODE REVIEW

**Comment by mattwire** [comment]
@artfulrobot This passes tests now - I've had to call contribution.create again to set some params - see comments in code

File: CRM/GoCardless/Page/Webhook.php [hunk 1]
```diff
@@ -208,10 +208,22 @@ public function doPaymentsConfirmed($event) {
...
-      civicrm_api3('Contribution', 'completetransaction', $contribution);
+      // Now call Payment.create. This will call Contribution.completetransaction internally
+      civicrm_api3('Payment', 'create', [
+        'contribution_id' => $contribution['id'],
+        'total_amount' => $contribution['total_amount'],
+        'trxn_date' => $payment->charge_date,
+        'trxn_id' => $payment->id,
+        'is_send_contribution_notification' => 0,
+      ]);
+      // @todo: At this point we want to save the trxn_id and receive_date to the contribution.
```
Comment (artfulrobot) [inline CRM/GoCardless/Page/Webhook.php:219]: Why is this `@todo`? Isn't it done by the next API call?

Comment (mattwire) [reply CRM/GoCardless/Page/Webhook.php:219]: `@fixme` instead? I don't like calling `Contribution.create` again because that call has quite a perfomance hit (which probably doesn't matter via IPN) and we should be looking at a "proper" CiviCRM core fix if appropriate in the future, or changing how the GoCardless extension handles things. But this fixes the problem.

Comment (artfulrobot) [reply CRM/GoCardless/Page/Webhook.php:219]: ok, so it's a @todo for core, not this extension. I think we just need to make this clear. I'll merge and update the comment.

I agree the core API is a bit unclear. It drives me nuts that it's not documented how it's supposed to be used/supposed to work, which is why I started [docs 735](https://github.com/civicrm/civicrm-dev-docs/pull/735).

**Review by artfulrobot — APPROVED** [review]
